/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 144db6b849b357665129a7a2b14d9d16)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		WORK_FACTOR: string;
		SIGNING_KEY: string;
		R2_PUBLIC_URL: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		R2: R2Bucket;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORK_FACTOR" | "SIGNING_KEY" | "R2_PUBLIC_URL">> {}
}
