/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 8ce952f36e4a4f09af56c1a070a32ef2)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		R2: R2Bucket;
		ASSETS: Fetcher;
		WORK_FACTOR: string;
		SIGNING_KEY: string;
		R2_PUBLIC_URL: string;
		GOOGLE_AUTH_CLIENT_ID: string;
		GOOGLE_AUTH_CLIENT_SECRET: string;
		GOOGLE_AUTH_RETURN_URL: string;
		GOOGLE_CONNECT_RETURN_URL: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORK_FACTOR" | "SIGNING_KEY" | "R2_PUBLIC_URL" | "GOOGLE_AUTH_CLIENT_ID" | "GOOGLE_AUTH_CLIENT_SECRET" | "GOOGLE_AUTH_RETURN_URL" | "GOOGLE_CONNECT_RETURN_URL">> {}
}
