/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 84e8f9949c7b8c9d04582905733e39ea)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
		durableNamespaces: "Database";
	}
	interface Env {
		WORK_FACTOR: string;
		SIGNING_KEY: string;
		DATABASE: DurableObjectNamespace<import("./src/worker").Database>;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WORK_FACTOR" | "SIGNING_KEY">> {}
}
